name = "     jai       "
dots = ".............."
print(name+dots) # it gives -->      jai     ..........
# So to remove these spaces we use strip method
# 1.) lstrip()
print(name.lstrip()+dots) # it gives -->jai     ..........

# 2.) rstrip()
print(name.rstrip()+dots) # it gives -->        jai........

#3.) strip()
print(name.strip()+dots) # it gives -->jai........

name1 = "     ja    i"
print(name1.strip()+dots) # it gives --> ja   i........
# it doesn't remove spaces between letters , so we have to replace it
print(name1.replace(" ","")+dots) # it gives --> jai........